plugins {
    id 'com.android.application'
}

android {
    namespace 'com.topdorama.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.topdorama.mobiletest'
        minSdk 24
        targetSdk 35
        versionCode 6
        versionName '0.6.0-test-fixed-signing'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
